#!/bin/bash
set -e
cd "${BASH_SOURCE%/*}"/..

echo "default snapshot"
stack test

for snapshot in 22.43 23.0 23.1 23.2 23.3; do
    echo "snapshot lts-$snapshot"
    stack test --snapshot "lts-$snapshot"
done

